language: php

matrix:
  allow_failures:
    - php: hhvm

php:
  - 5.4
  - 5.5
  - hhvm

before_script:
  - composer self-update
  - composer install --dev
  - mysql -uroot -e "CREATE DATABASE php_analyzer CHARACTER SET utf8 COLLATE utf8_general_ci"
  - "sed -i 's/<\\!--//g' phpunit.xml.dist"
  - "sed -i 's/-->//g' phpunit.xml.dist"

script: phpunit 
